# Generated by Django 5.1.3 on 2025-03-20 05:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="gender",
            field=models.CharField(default="F", max_length=10),
            preserve_default=False,
        ),
    ]
